In [ ]:
%%HTML
<h1><marquee><font color='green'>Welcome to the Journey of Data Science

##Indexing over numpy array

In [ ]:
import numpy as np 

In [ ]:
a= np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
#indexing default works on rows
a[3] # If we want last row

array([15, 16, 17, 18, 19])

In [ ]:
a[-1] #-ve indexing

array([15, 16, 17, 18, 19])

In [ ]:
#If we want to access no in row, suppose we want 16, then 1st no for row index and second for no's index
a[-1,1]

16

In [ ]:
a[0,1] #access row with index 0 and element present at index 1

1

In [ ]:
a[[0,1]] #access rows with index 0 and 1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
a[[0,3,2]]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14]])

##**Lets work on column**
indexing only works on rows
and it works on element within that row
But if I want to work on columns then indexing fails
So, will go with slicing option

## **Slicing**

Array[Start point:Stop point:stepping]

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
#using slicing access rows, it returns whole array
a[:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
#reverse
a[::-1]

array([[15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [ ]:
a[::2]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a[::-2]

array([[15, 16, 17, 18, 19],
       [ 5,  6,  7,  8,  9]])

#to work on Column use a[:,:]==> [rows,columṇs]

In [ ]:
a[:,:]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
#all rows and 1st column
a[:,[0]] 

array([[ 0],
       [ 5],
       [10],
       [15]])

In [ ]:
a[0] 

array([0, 1, 2, 3, 4])

In [ ]:
a[:1:]

array([[0, 1, 2, 3, 4]])

In [ ]:
a[:,0] #1st column

array([ 0,  5, 10, 15])

In [ ]:
a[:,[1]]

array([[ 1],
       [ 6],
       [11],
       [16]])

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
#access last column
a[:,-1]

array([ 4,  9, 14, 19])

In [ ]:
a[:,[-1]]

array([[ 4],
       [ 9],
       [14],
       [19]])

In [ ]:
#Want last 2 column
a[:,[-1,-2]]

array([[ 4,  3],
       [ 9,  8],
       [14, 13],
       [19, 18]])

In [ ]:
# i want to access 1st 3 columns
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a[:,:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])

#**Start index of row:end index of row,start column:end column**

In [ ]:
#access last 3 columns
a[:,2:]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [ ]:
# reverse the columns
a[:,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [ ]:
#without slicing reverse the columns
a[:,[-1,-2,-3,-4,-5]]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [ ]:
a[:,[4,3,2,1,0]]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15]])

In [ ]:
#access 1st column, last column,middle 2 colums
#sequence: 0,4,2,3
a[:,[0,4,2,3]]

array([[ 0,  4,  2,  3],
       [ 5,  9,  7,  8],
       [10, 14, 12, 13],
       [15, 19, 17, 18]])

#Work on row and colums now

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
"""
8, 9],
13, 14]
"""
a[1:3,3:]

array([[ 8,  9],
       [13, 14]])

In [ ]:
a[1:3,-2:]

array([[ 8,  9],
       [13, 14]])

In [ ]:
#access corner elements
# 0,4,15,19
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a[::3,::4]

array([[ 0,  4],
       [15, 19]])

In [ ]:
a.shape
#while accessing corner element in 2D array substract 1 from shape
# and do the stepping 

(4, 5)

In [ ]:
#indexing way
a[[0,-1],[0,-1]]

array([ 0, 19])

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a[0,4]

4

In [ ]:
a[[0,-1],::4]

array([[ 0,  4],
       [15, 19]])

In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a[:3,:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [ ]:
#change corner elements to 0
a[::3,::4]

array([[ 0,  4],
       [15, 19]])

In [ ]:
a[::3,::4] =0

In [ ]:
a

array([[ 0,  1,  2,  3,  0],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [ 0, 16, 17, 18,  0]])

In [ ]:
# convert 2nd column values to 10
a[:,[1]] = 10

In [ ]:
a

array([[ 0, 10,  2,  3,  0],
       [ 5, 10,  7,  8,  9],
       [10, 10, 12, 13, 14],
       [ 0, 10, 17, 18,  0]])

In [ ]:
#convert the values of  2nd last column  in order [1,2,3,4]
a[:,1] = [1,2,3,4]
a

array([[ 0,  1,  2,  3,  0],
       [ 5,  2,  7,  8,  9],
       [10,  3, 12, 13, 14],
       [ 0,  4, 17, 18,  0]])

In [ ]:
#change corner elements as 100,200,300,400
a[::3,::4] = [[100, 200],
              [300, 400]]

In [ ]:
a

array([[100,   1,   2,   3, 200],
       [  5,   2,   7,   8,   9],
       [ 10,   3,  12,  13,  14],
       [300,   4,  17,  18, 400]])

In [ ]:
#convert rows to column n vice versa
np.transpose(a)

array([[100,   5,  10, 300],
       [  1,   2,   3,   4],
       [  2,   7,  12,  17],
       [  3,   8,  13,  18],
       [200,   9,  14, 400]])

In [ ]:
a.T

array([[100,   5,  10, 300],
       [  1,   2,   3,   4],
       [  2,   7,  12,  17],
       [  3,   8,  13,  18],
       [200,   9,  14, 400]])