#Different ways to create numpy arrays :
*   np.array()
*   np.ones()
*   np.zeros()
*   np.full()
*   np.arange()
*   np.range()
*   np.linspace()






While creating an array we give shape in tuple format i.e. (2,2)

# **If we want to create random data, array we use numpy**

In [58]:
import numpy as np

In [40]:
np.array([[10,20],[30,40]])

array([[10, 20],
       [30, 40]])

In [41]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [43]:
np.full((2,2), fill_value=22)

array([[22, 22],
       [22, 22]])

In [44]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(1,10,5)

array([1, 6])

In [47]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.array(range(1,10,5))

array([1, 6])

In above example, we observered that 3 variables means start point, end point and stepping.

In [50]:
np.linspace(1,10,5)  #and n this example last variable represents frequency.

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#Create an array with random numbers

In [51]:
 """
Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0)
"""
np.random.random(5)

array([0.86942594, 0.10643709, 0.52174802, 0.45250459, 0.93299013])

With the help of random method we can create aaray of given size but umbers are only between 0 and 1.

In [52]:
np.random.random((1,2,2)) #1 block, 2 rows and 2 coloms

array([[[0.58615629, 0.83796204],
        [0.53655789, 0.79681828]]])

#np.random.randn()
Gives values between -3 to 3

In [53]:
np.random.randn(20)

array([-0.27997713, -0.36080427, -1.33964863,  0.96005734,  1.38958815,
       -0.80720935, -0.59239599,  0.7056974 , -0.32766581,  0.22095529,
       -1.22193014, -1.64703998,  0.07079095, -1.13823736,  0.00940304,
       -0.35003453,  0.9955765 , -2.30241881,  0.75871268,  0.08269486])

In [54]:
np.random.randn(2,3)

array([[-0.63565635,  0.12127551, -0.61775845],
       [ 0.63329438,  0.98771952,  0.26127172]])

Docstring:
#randint(low, high=None, size=None, dtype=int)

* Return random integers from `low` (inclusive), means low value present in the output to `high` (exclusive) and high value will not be present in the output.

* Return random integers from the "discrete uniform"

* np.random.randint(low=4,high=15) , This will return single number between 4 to 15

In [55]:
np.random.randint(low=4,high=15)

8

In [56]:
# Supply Size
np.random.randint(low=6,high=15,size=30)

array([13,  8,  8, 13,  8, 11, 11,  9,  6,  9, 11,  7, 12,  6,  6, 11, 11,
        9,  8, 14, 12,  7,  6,  7, 12, 11, 11, 14,  7,  6])

**We use this methods for random record generation**

In [57]:
# Create array with empty method
np.empty(10)

array([-1.31693399,  2.07308396,  1.01097704,  0.2358356 , -0.20717177,
        0.81826562,  1.45234729, -0.55337342, -1.72076303, -0.87913277])

**It will take numbers present in memory and it it won't find numbers then it will give garbage values**

In [73]:
#Create array with same dimensions and shape
a=np.random.random((2,2))
a

array([[0.9291527 , 0.12690249],
       [0.88228967, 0.94553786]])

In [74]:
a.shape

(2, 2)

In [78]:
a=np.arange(4).reshape(2,2)
a

array([[0, 1],
       [2, 3]])

In [79]:
np.ones_like(a) #TO change the numbers into one it will create new copy of array, same used for empty_like, zeros_like

array([[1, 1],
       [1, 1]])

In [80]:
a  # a array not changed means we have to store this output into new variable

array([[0, 1],
       [2, 3]])

Statistical/Mathematical operation :

In [81]:
a

array([[0, 1],
       [2, 3]])

#sum()

In [82]:
a.sum() #Addition of all nos

6

In [83]:
#row-wise addition
a.sum(axis=1) 

array([1, 5])

In [84]:
#Colomn-wise addition
a.sum(axis=0)

array([2, 4])

#**Mean()**
sum of total no / count of numbers, also called as average.

In [86]:
# mean()--take the avg of nos

a.mean()

1.5

In [87]:
a.mean(axis=1) #row-wise mean

array([0.5, 2.5])

In [88]:
a.mean(axis=0) #Colomn-wise mean

array([1., 2.])

#Q. **what are different central measures of tendencies?**
--> mean, median, mode


#**median**
median means middle value, if we have even nos then it will take avg of middle 2 nos. But catch is here that, it will first sort the array values into asending order then gives us middle value/avg of middle value.
(a+b)/2

In [89]:
a

array([[0, 1],
       [2, 3]])

In [93]:
np.median(a) 
# Here, we dont have direct median method present in numpy array so we access this method with different approch.
# e.g we can't access as a.median() so we access it as np.median(a) 

1.5

#**mode**
Most frequent element/value.
You can have more than one mode.
module 'numpy' has no attribute 'mode'

In [95]:
help(a.std)

Help on built-in function std:

std(...) method of numpy.ndarray instance
    a.std(axis=None, dtype=None, out=None, ddof=0, keepdims=False, *, where=True)
    
    Returns the standard deviation of the array elements along given axis.
    
    Refer to `numpy.std` for full documentation.
    
    See Also
    --------
    numpy.std : equivalent function



In [96]:
a.std()

1.118033988749895

In [97]:
a.std(axis=1)

array([0.5, 0.5])

In [100]:
a

array([[0, 1],
       [2, 3]])

In [98]:
a.min()


0

In [99]:
a.max()

3

# Operations over numpy array

In [101]:
#add 1000 in each number
#elementwise addition 
np.add(a,1000)

array([[1000, 1001],
       [1002, 1003]])

In [107]:
np.multiply(a,1000)

array([[   0, 1000],
       [2000, 3000]])

In [108]:
np.divide(a,1000)

array([[0.   , 0.001],
       [0.002, 0.003]])

In [109]:
np.power(a,2)

array([[0, 1],
       [4, 9]])

In [110]:
np.mod(a,2)

array([[0, 1],
       [0, 1]])

In [ ]:
help(np.mod) #Gives reminder a%2

In [102]:
a + 1000
#use += and see the result, this is python operator method

array([[1000, 1001],
       [1002, 1003]])

In [103]:
a #all above ops are temp., they are not chaning original array

array([[0, 1],
       [2, 3]])

In [104]:
p = np.array([[10,20],[30,40]])
p

array([[10, 20],
       [30, 40]])

In [106]:
np.add(a,p)

array([[10, 21],
       [32, 43]])

In [112]:
np.subtract(a,p)

array([[-10, -19],
       [-28, -37]])

In [113]:
np.multiply(a,p)

array([[  0,  20],
       [ 60, 120]])

In [114]:
np.divide(a,p)

array([[0.        , 0.05      ],
       [0.06666667, 0.075     ]])