In [1]:
import numpy as np

#np.linspace(): used to create a sequence of numbers with constant spacing or linear spacing between 2 numbers



In [ ]:
"""
Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].
"""

In [ ]:
np.linspace(1,15)
# 1 to 15 numbers, please note here 15 is included due to endpoint is TRUE i.e stop is inclusive, if exclusive then 15 will not be present.
# Also the difference between the two consecutive nos is same for all.
#def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

array([ 1.        ,  1.28571429,  1.57142857,  1.85714286,  2.14285714,
        2.42857143,  2.71428571,  3.        ,  3.28571429,  3.57142857,
        3.85714286,  4.14285714,  4.42857143,  4.71428571,  5.        ,
        5.28571429,  5.57142857,  5.85714286,  6.14285714,  6.42857143,
        6.71428571,  7.        ,  7.28571429,  7.57142857,  7.85714286,
        8.14285714,  8.42857143,  8.71428571,  9.        ,  9.28571429,
        9.57142857,  9.85714286, 10.14285714, 10.42857143, 10.71428571,
       11.        , 11.28571429, 11.57142857, 11.85714286, 12.14285714,
       12.42857143, 12.71428571, 13.        , 13.28571429, 13.57142857,
       13.85714286, 14.14285714, 14.42857143, 14.71428571, 15.        ])

In [ ]:
#if we want only 20 numbers betwen 1-15
np.linspace(1,10,num=20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [ ]:
#if we set endpoint=False
#then stop wont be a part of output, 15 wil not be present
np.linspace(1,15,num=20,endpoint=False)

array([ 1. ,  1.7,  2.4,  3.1,  3.8,  4.5,  5.2,  5.9,  6.6,  7.3,  8. ,
        8.7,  9.4, 10.1, 10.8, 11.5, 12.2, 12.9, 13.6, 14.3])

In [ ]:
#to check difference btwn 2 values set retstep=True
np.linspace(1,15,num=20,retstep=True,endpoint=False)

(array([ 1. ,  1.7,  2.4,  3.1,  3.8,  4.5,  5.2,  5.9,  6.6,  7.3,  8. ,
         8.7,  9.4, 10.1, 10.8, 11.5, 12.2, 12.9, 13.6, 14.3]),
 0.7)

In [ ]:
help(np.linspace)

**np.append():to append elements at the end**

In [ ]:
a=np.array([10,20,30])
a

array([10, 20, 30])

In [ ]:
"""
Signature: np.append(arr, values, axis=None)
Docstring:
Append values to the end of an array.
"""
np.append(a,100)

array([ 10,  20,  30, 100])

In [ ]:
np.append(a,[20,50,70])

array([10, 20, 30, 20, 50, 70])

In [ ]:
b=np.random.random((3,5))
b

array([[0.77520634, 0.1430219 , 0.62363598, 0.66580562, 0.83301111],
       [0.59715955, 0.48678799, 0.56269872, 0.5063392 , 0.00686544],
       [0.1647478 , 0.602981  , 0.75217537, 0.64069207, 0.60302532]])

In [ ]:
b.shape

(3, 5)

In [ ]:
#add values in row
np.append(b,[[1,2,3,4,5]],axis=0)
#Here, we need to give an axis, for row=0, colomn=1, Also keep in mind that we have to give nos according to shape of our array.
# i.e 5 nos in row, need to give 5 values. 

array([[0.77520634, 0.1430219 , 0.62363598, 0.66580562, 0.83301111],
       [0.59715955, 0.48678799, 0.56269872, 0.5063392 , 0.00686544],
       [0.1647478 , 0.602981  , 0.75217537, 0.64069207, 0.60302532],
       [1.        , 2.        , 3.        , 4.        , 5.        ]])

In [ ]:
b #Changes are temp, Rememberrrrrrrr

array([[0.77520634, 0.1430219 , 0.62363598, 0.66580562, 0.83301111],
       [0.59715955, 0.48678799, 0.56269872, 0.5063392 , 0.00686544],
       [0.1647478 , 0.602981  , 0.75217537, 0.64069207, 0.60302532]])

In [ ]:
#Add values in colomn
np.append(b,[[1],[2],[2]],axis=1)

array([[0.77520634, 0.1430219 , 0.62363598, 0.66580562, 0.83301111,
        1.        ],
       [0.59715955, 0.48678799, 0.56269872, 0.5063392 , 0.00686544,
        2.        ],
       [0.1647478 , 0.602981  , 0.75217537, 0.64069207, 0.60302532,
        2.        ]])

# **np.cumsum: cummulative sum**

In [ ]:
b.cumsum()

array([0.77520634, 0.91822824, 1.54186422, 2.20766984, 3.04068095,
       3.6378405 , 4.12462849, 4.68732721, 5.19366641, 5.20053184,
       5.36527964, 5.96826064, 6.72043601, 7.36112808, 7.9641534 ])

In [5]:
c = np.array([1,-2,3,4,5])
c

array([ 1, -2,  3,  4,  5])

In [6]:
c.cumsum()

array([ 1, -1,  2,  6, 11])

In [9]:
# If we want row wise or column wise cumsum then use axis
d=np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
d.cumsum(axis=1)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [10]:
d.cumsum(axis=0)

array([[1, 2, 3],
       [5, 7, 9]])

In [11]:
#cumprod()
d=d.cumprod()
d

array([  1,   2,   6,  24, 120, 720])

#np.delete: to delete an element from an array

In [ ]:
"""
Signature: np.delete(arr, obj, axis=None)
arr: means an array from which we want to delete elements
obj: index of element to delete
Docstring:
Return a new array with sub-arrays along an axis deleted. For a one
dimensional array, this returns those entries not returned by
"""
#delete 4
d

array([       1,        2,       12,      288,    34560, 24883200])

In [ ]:
np.delete(d,2)

array([       1,        2,      288,    34560, 24883200])

In [ ]:
d #operations gives u an output but its temp. output not permanent

array([       1,        2,       12,      288,    34560, 24883200])

In [ ]:
b

array([[0.77520634, 0.1430219 , 0.62363598, 0.66580562, 0.83301111],
       [0.59715955, 0.48678799, 0.56269872, 0.5063392 , 0.00686544],
       [0.1647478 , 0.602981  , 0.75217537, 0.64069207, 0.60302532]])

In [ ]:
#remove a row: middle row
np.delete(b,1,axis=0)

array([[0.77520634, 0.1430219 , 0.62363598, 0.66580562, 0.83301111],
       [0.1647478 , 0.602981  , 0.75217537, 0.64069207, 0.60302532]])

In [ ]:
#remove a last column
np.delete(b,-1,axis=1)

array([[0.77520634, 0.1430219 , 0.62363598, 0.66580562],
       [0.59715955, 0.48678799, 0.56269872, 0.5063392 ],
       [0.1647478 , 0.602981  , 0.75217537, 0.64069207]])

#np.insert: too add element in between

In [ ]:
"""
Signature: np.insert(arr, obj, values, axis=None)
Docstring:
Insert values along the given axis before the given indices.
"""
#add 30 in index 2 
np.insert(d,2,30)

array([       1,        2,       30,       12,      288,    34560,
       24883200])

In [ ]:
np.insert(d,2,range(4))

array([       1,        2,        0,        1,        2,        3,
             12,      288,    34560, 24883200])

In [ ]:
d=np.array([[1,2,3],[4,5,6]])
d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
#insert new data before 2nd column
np.insert(d,1,[33,44],axis=1)

array([[ 1, 33,  2,  3],
       [ 4, 44,  5,  6]])

In [ ]:
#insert a new data in each column and requiremnt is to add
np.insert(d,1,range(1,4),axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [ ]:
d

array([[1, 2, 3],
       [4, 5, 6]])

#np.where: condition based conversion we can carry out

In [ ]:
p = np.arange(24).reshape(6,4)
p

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
"""
Docstring:
where(condition, [x, y])

Return elements chosen from `x` or `y` depending on `condition`.

if condition is True return x else return y
"""
# return 0 if value<12
np.where(p<12,0,p)

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
#value>=18 +ve and remaining -ve
np.where(p>=18,-p,p)

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17, -18, -19],
       [-20, -21, -22, -23]])

In [ ]:
# convert in 0 and 1 form
#value>10 ==> 0
# else 1
np.where(p>10,0,1)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])