# Numpy Introduction

- It is termed as Numeric Python/Numerical python
- Which is dedicatedly used to deal with numbers
- Its background data strcuture is an array(indexing+slicing)
- Its mutable in nature

In [ ]:
#check version of a numpy
import numpy
numpy.__version__

'1.20.3'

In [ ]:
#import 
import numpy as np

In [ ]:
np

<module 'numpy' from 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

# Create numpy array

## np.array()

In [ ]:
np.array()
#to see the details of any method use: shift+tab

In [ ]:
#2nd approach is
np.array?
#run this using shift+enter

#np.array(object,dtype)

In [ ]:
np.array(1000)

array(1000)

In [ ]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [ ]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

### check some properties of an array 'a'


In [ ]:
#type of array
type(a)
#Q. what is type of numpy array?
#Ans: ndarray (n dimensional array)

numpy.ndarray

In [ ]:
#check dimensions
a.ndim

1

In [ ]:
# check total element present in a
a.size

5

In [ ]:
len(a)

5

In [ ]:
print(a.size)
print(a.ndim)

5
1


In [ ]:
display(a.ndim,a.size)

1

5

In [ ]:
#check data type
a.dtype

dtype('int32')

In [ ]:
# check rows and columns number if any
a.shape

(5,)

In [ ]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.shape

(2, 3)

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
a.shape

(5,)

In [ ]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
b.shape

(2, 3)

In [ ]:
c = np.array(a,ndmin=2)
c

array([[1, 2, 3, 4, 5]])

In [ ]:
c.shape

(1, 5)

In [ ]:
a

array([1, 2, 3, 4, 5])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
#shape should be in tuple
(5)

5

In [ ]:
(5,)

(5,)

### use dtype

In [ ]:
np.array([10,20,30])

array([10, 20, 30])

In [ ]:
#int to float: upcasting
np.array([10,20,30],dtype='float')

array([10., 20., 30.])

In [ ]:
np.array([10,20,30],dtype='complex')

array([10.+0.j, 20.+0.j, 30.+0.j])

In [ ]:
#if we have float values
np.array([2.3,4.66,7.80,9.10])

array([2.3 , 4.66, 7.8 , 9.1 ])

In [ ]:
#convert float to int: downcasting
np.array([2.3,4.66,7.80,9.10],dtype='int')

array([2, 4, 7, 9])

In [ ]:
#numeric: order of datatypes
# int--> float-->complex

In [ ]:
#implitcite typecasting
np.array([1,2,3,4,5.])

array([1., 2., 3., 4., 5.])

In [ ]:
np.array([1,2,35,5+6j])

array([ 1.+0.j,  2.+0.j, 35.+0.j,  5.+6.j])

In [ ]:
np.array([1,2,35,5+6j])

array([ 1.+0.j,  2.+0.j, 35.+0.j,  5.+6.j])

## np.zeros(): creates an array of 0's

In [ ]:
#1D
np.zeros(9) #9: total number of zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#2D
np.zeros((2,4))#(2 rows,4 columns)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#3D
np.zeros((3,2,2))#(3 blocks,2 rows,2 columns)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
np.zeros((3,2,2),dtype='int')

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

### np.ones()

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## np.full(): creates an array with constant value


In [ ]:
np.full(4,fill_value=99)

array([99, 99, 99, 99])

In [ ]:
#2D
np.full((4,4),fill_value=77)

array([[77, 77, 77, 77],
       [77, 77, 77, 77],
       [77, 77, 77, 77],
       [77, 77, 77, 77]])

In [ ]:
np.full((3,3),fill_value=22)

array([[22, 22, 22],
       [22, 22, 22],
       [22, 22, 22]])

## np.arange(): same as that of range() in python

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Q.range() vs arange()

In [ ]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
np.arange(1,21,2) #odd numbers

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
#-ve stepping
np.arange(20,0,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3,  2,  1])

In [ ]:
#-ve stepping: even numbers in reverse order 
np.arange(20,0,-2)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])