In [1]:
# Q. Create an array of random numbers
import numpy as np

In [2]:
np.random.random(5)

array([0.41009153, 0.0022385 , 0.79752348, 0.51694014, 0.51464509])

In [4]:
np.random.random((2,4))

array([[0.61370663, 0.04050074, 0.92845114, 0.07984659],
       [0.25864382, 0.80245317, 0.1306422 , 0.7628468 ]])

In [5]:
# Q. Create an array of ranndom int values between range 10,20
np.random.randint(low=10,high=20,size=10)

array([16, 15, 18, 13, 18, 10, 12, 18, 14, 15])

In [6]:
np.random.randint(10,20,20)

array([10, 17, 19, 17, 16, 10, 19, 18, 15, 16, 15, 12, 11, 15, 12, 17, 11,
       12, 11, 16])

In [8]:
a=np.arange(20).reshape(4,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [10]:
# Q.  Fetch elements > 15

a[a>15]

array([16, 17, 18, 19])

In [11]:
a>15  #It will give output in boolean

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True]])

In [14]:
# Q. Fetch/Return value >18 and value <5
a[(a>18) | (a<5)]

array([ 0,  1,  2,  3,  4, 19])

In [15]:
x = np.array([18,20,29,35,89,70,100])
x

array([ 18,  20,  29,  35,  89,  70, 100])

In [17]:
x[(x%5 == 0) & (x%7 == 0)]

array([35, 70])

In [18]:
#Q. Create 4x4 array with all value set to True
np.full((4,4), fill_value=True)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [19]:
np.ones((4,4), dtype=bool)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
np.full((5,5), fill_value=False)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [23]:
np.zeros((5,5), dtype=bool)

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [24]:
#Q. Create a 4x4 array with Digonal elements True and Non Diagonal element False
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
np.identity((5), dtype=bool)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

In [ ]:
#Q. Create a 4x4 array with Digonal elements False and Non Diagonal element True

In [26]:
~ np.identity((5), dtype=bool)

array([[False,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True, False,  True],
       [ True,  True,  True,  True, False]])

In [27]:
np.eye(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [28]:
~ np.eye(4,dtype=bool)

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])

In [29]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [30]:
a[::2] # This is stepping by 2 means, it will start with 0th row then jump on row start with 8 and 16 because it is step by 2.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [ ]:
# Q. Access /return diagonal elements from an array 'a'

In [37]:
np.diagonal(a)

array([ 0,  6, 12, 18])

In [32]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [48]:
#Q. set diagonal elements to -1
np.fill_diagonal(a,val=-1)
a

array([[-1,  1,  2,  3,  4],
       [ 5, -1,  7,  8,  9],
       [10, 11, -1, 13, 14],
       [15, 16, 17, -1, 19]])

# New section

In [49]:
# Q. Reverse columns and rows as well 
a[::-1,::-1]

array([[19, -1, 17, 16, 15],
       [14, 13, -1, 11, 10],
       [ 9,  8,  7, -1,  5],
       [ 4,  3,  2,  1, -1]])

In [51]:
a

array([[-1,  1,  2,  3,  4],
       [ 5, -1,  7,  8,  9],
       [10, 11, -1, 13, 14],
       [15, 16, 17, -1, 19]])

In [53]:
#reverse rows only
a[::-1,:]

array([[15, 16, 17, -1, 19],
       [10, 11, -1, 13, 14],
       [ 5, -1,  7,  8,  9],
       [-1,  1,  2,  3,  4]])

In [54]:
#reverse Column only
a[:,::-1 ]

array([[ 4,  3,  2,  1, -1],
       [ 9,  8,  7, -1,  5],
       [14, 13, -1, 11, 10],
       [19, -1, 17, 16, 15]])

In [55]:
#Q. return an index of max. element
# means at which index max. element is present???
np.argmax(a)

19

In [61]:
a

array([[-1,  1,  2,  3,  4],
       [ 5, -1,  7,  8,  9],
       [10, 11, -1, 13, 14],
       [15, 16, 17, -1, 19]])

In [58]:
# Now if we want to findout index of a max element rowwise
np.argmax(a, axis=0) #It gives index not element, also here if we want row wise max index use axis=0

array([3, 3, 3, 2, 3])

In [59]:
x

array([ 18,  20,  29,  35,  89,  70, 100])

In [60]:
np.argmax(x)

6

In [62]:
np.argmin(x)

0

In [ ]:
#we can apply trignometry functions like sin cos tan over numpy array

In [63]:
np.sin(a)

array([[-0.84147098,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.84147098,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.84147098,  0.42016704,  0.99060736],
       [ 0.65028784, -0.28790332, -0.96139749, -0.84147098,  0.14987721]])

In [64]:
np.identity(4,dtype=bool)

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [65]:
#To reverse the above output
np.invert(np.identity(4,dtype=bool))

array([[False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True, False]])